name: my-first-workflow
on: workflow_dispatch
jobs: 
  first-job: 
    runs-on: ubuntu-latest
    steps: 
      - name: print greetings
        run: echo " hello welcome to first action "
      - name: print good bye
...
        run: |
    echo "First output"
    echo "Second output"
